### ISSUE TITLE
can you update it for swift 3.0.1 ?

### ISSUE THREAD

**Issue by h1257977** [goloveychuk/SwiftOracle#2]

**Comment by goloveychuk** [comment]
hm, anybody uses it.
I can update to compile for 3.0.1, but not able to test it.

**Comment by h1257977** [comment]
please update it, i 'll test it and let u know

**Comment by goloveychuk** [comment]
@h1257977 #3

**Comment by h1257977** [comment]
need to correct these small warning and errors:

/home/lip/for_oracle/Packages/SwiftOracle-0.1.5/Sources/SwiftOracle/Row.swift:42:26: error: 'String' is not convertible to 'AnyObject'; did you mean to use 'as!' to force downcast?
            return "asd" as AnyObject
                   ~~~~~~^~~~~~~~~~~~
                         as!
/home/lip/for_oracle/Packages/SwiftOracle-0.1.5/Sources/SwiftOracle/Connection.swift:115:19: warning: value 'connection' was defined but never used; consider replacing with boolean test
        guard let connection = connection else {
              ~~~~^~~~~~~~~~~~~
                                          != nil
