### ISSUE TITLE
can you update  it for swift 4

### ISSUE THREAD

**Issue by h1257977** [goloveychuk/SwiftOracle#4]
your project is  very helpful for SSS who wanna connect to oracle database. Can you please update your code to accommodate for swift 4

**Comment by goloveychuk** [comment]
I've just compiled it with 
`Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)`
with no issues. 
Can you explain, what you mean by ` accommodate for swift 4`

**Comment by santhoshios** [comment]
can u please tell me which podfile are using..
you are not mention podfile so how can we develope,

**Comment by goloveychuk** [comment]
@santhoshios it's using swift package manager

**Comment by santhoshios** [comment]
could you please share the screen shots how to use..
please it's really very urgent for me.
i hope you am getting positive response...

**Comment by goloveychuk** [comment]
https://swift.org/package-manager/
also SwiftOracle is not production ready. I don't know why you can be urgent on this

**Comment by santhoshios** [comment]
Thank you Mr.
In my office the java developers used Oracle database...
Now, i'm developing a iOS mobile application,
for that i wanna fetch data and store from Oracle Database.
please tell me, Is it possible to fetch & save the details to Oracle
Database using through  iOS mobile application or Android application?

**Comment by goloveychuk** [comment]
you should write a backend for your ios app. It's unsafe to make a direct connection to db from mobile app.

**Comment by goloveychuk** [comment]
this library is for backend apps, written in swift language.

**Comment by h1257977** [comment]
> 
> 
> I've just compiled it with
> `Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)`
> with no issues.
> Can you explain, what you mean by ` accommodate for swift 4`

It was crashing for me when run with swift 4  . I guess it still throws error with swift 4.2 too. Can you check it? And is  your method applicable  with unicodes too?

**Comment by h1257977** [comment]
how do you run stored procedure in this library ? Any examples ?

**Comment by goloveychuk** [comment]
@h1257977 just to check, how you're going to use this library? You're writing ios app or backend on swift?

**Comment by h1257977** [comment]
i an using it with vapor

**Comment by h1257977** [comment]
i am following this link, but its a simple select statement.  I am looking to execute stored procedure.
https://www.reddit.com/r/swift/comments/5492cr/does_server_side_swift_has_driver_for_oracle/

**Comment by goloveychuk** [comment]
I see. I currently don't have time to support this library. It's not stable, no error catching, reconnecting and other hundreds of edge cases. You shouldn't use it on production. Only if you have enough time to invest on development. 
SwiftOracle is wrapper of ocilib. If you need stored procedures, please look at ocilib library, find proper method and write its wrapper on swift.
